/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import ClassesdoProjProgIII.Familia;
import ClassesdoProjProgIII.Poupanca;
import static VisaodoProjProgIII.Login.saldo;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.PoupancaBD;
import controlo.PrevisaoBD;
import controlo.RendimentoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Adc_Valores_Pou extends javax.swing.JFrame {
RendimentoBD rendimentos = new RendimentoBD();
    /**
     * Creates new form Adc_Valores_Pou
     */
    public Adc_Valores_Pou() throws SQLException {
        
            initComponents();
            setSize(1240, 742);
            dispose();
            float desc1=PrevisaoBD.descontos1(idpessoa);
            float desc2=PrevisaoBD.descontos2(idfamilia);
            Login.saldo= RendimentoBD.somaRendimentos(idpessoa)-(desc1+desc2);
            System.out.println(Float.toString(saldo));
            System.out.println(idpessoa);
            System.out.println(idfamilia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        dataPou = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorPou = new javax.swing.JTextField();
        motivoPou = new javax.swing.JTextField();
        adc_valoresPou = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("YYYY/MM/DD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 350, 110, 20);
        getContentPane().add(dataPou);
        dataPou.setBounds(600, 370, 250, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("DATA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 380, 60, 20);
        getContentPane().add(valorPou);
        valorPou.setBounds(600, 310, 250, 40);
        getContentPane().add(motivoPou);
        motivoPou.setBounds(600, 430, 250, 40);

        adc_valoresPou.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adc_valoresPou.setText("ADICIONAR VALOR");
        adc_valoresPou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adc_valoresPouActionPerformed(evt);
            }
        });
        getContentPane().add(adc_valoresPou);
        adc_valoresPou.setBounds(510, 560, 200, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("MOTIVO ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 440, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("VALOR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 320, 80, 20);

        Voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(100, 620, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/Adicionar Valores.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1240, 720);

        setSize(new java.awt.Dimension(1262, 774));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Poupancas().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void adc_valoresPouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adc_valoresPouActionPerformed
        // TODO add your handling code here:
        
        String v= valorPou.getText();
        String motivoP= motivoPou.getText();
        String dataP= dataPou.getText();        
        float valorP = Float.parseFloat(v);
        float desc1;
    try {
        desc1 = PrevisaoBD.descontos1(idpessoa) + PrevisaoBD.somaPrev(idfamilia) + PrevisaoBD.descontos2(idfamilia);
        Login.saldo= RendimentoBD.somaRendimentos(idpessoa)-(desc1);
    } catch (SQLException ex) {
        Logger.getLogger(Adc_Valores_Pou.class.getName()).log(Level.SEVERE, null, ex);
    }   
        if(valorP<=Login.saldo){
            Poupanca p=new Poupanca(motivoP, valorP, dataP);
            PoupancaBD pou = new PoupancaBD();
            Familia f = new Familia(null, null, null, null);
            Login.saldo=Login.saldo-valorP;
            f.setIdFamilia(idfamilia);
            p.setFamilia(f);
            pou.adicionarPoupanca(p);
            dispose();
            new Poupancas().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Valor da Poupança superior ao rendimento");
        }
    }//GEN-LAST:event_adc_valoresPouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adc_Valores_Pou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adc_Valores_Pou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adc_Valores_Pou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adc_Valores_Pou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Adc_Valores_Pou().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Adc_Valores_Pou.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton adc_valoresPou;
    private javax.swing.JTextField dataPou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField motivoPou;
    private javax.swing.JTextField valorPou;
    // End of variables declaration//GEN-END:variables
}
