/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import ClassesdoProjProgIII.GastosInd;
import ClassesdoProjProgIII.Humanos;
import ClassesdoProjProgIII.PrevMensal;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.GastosI;
import controlo.PrevisaoBD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */

public class Adc_Gastos extends javax.swing.JFrame {

    /**
     * Creates new form Adc_Gastos
     */
    public static float soma = 0.0f;
    PrevisaoBD prev = new PrevisaoBD();
    public Adc_Gastos() throws SQLException {
        initComponents();
        setSize(1260, 775);
        dispose();
        lerTabela();
    }
      public ArrayList<GastosInd> gastos = new  ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
       public void lerTabela () throws SQLException {
           
               DefaultTableModel tb= (DefaultTableModel) tabelaPr.getModel();  
               tb.setNumRows(0);
              
               for(PrevMensal pr:prev.lerP(idfamilia)){
                    tb.addRow(new Object[]{pr.getId(), pr.getNomeDoGasto(), pr.getValor()});
               }
        
       }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPr = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        adicionar_Gasto = new javax.swing.JButton();
        localGasto = new javax.swing.JTextField();
        dataGasto = new javax.swing.JTextField();
        designacaoDoGasto = new javax.swing.JTextField();
        valorDoGasto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setText("Fazer Credito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 520, 150, 29);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(940, 680, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("TABELAS DAS PREVISÕES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 490, 310, 30);

        tabelaPr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tabelaPr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "NOME DO GASTO", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 520, 630, 190);

        jLabel6.setText("YYYY/MM/DD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 350, 120, 20);

        adicionar_Gasto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adicionar_Gasto.setText("GASTAR");
        adicionar_Gasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionar_GastoMouseClicked(evt);
            }
        });
        adicionar_Gasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_GastoActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar_Gasto);
        adicionar_Gasto.setBounds(500, 430, 210, 40);
        getContentPane().add(localGasto);
        localGasto.setBounds(720, 310, 240, 40);
        getContentPane().add(dataGasto);
        dataGasto.setBounds(720, 370, 240, 40);

        designacaoDoGasto.setEditable(false);
        getContentPane().add(designacaoDoGasto);
        designacaoDoGasto.setBounds(270, 320, 240, 40);

        valorDoGasto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                valorDoGastoCaretUpdate(evt);
            }
        });
        getContentPane().add(valorDoGasto);
        valorDoGasto.setBounds(270, 370, 240, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("DATA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 380, 47, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("LOCAL DO GASTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 320, 144, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("VALOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 380, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("DESIGNAÇÃO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 330, 120, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 620, 140, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(940, 640, 140, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/ADICIONAR GASTOR DIARIOS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1240, 720);

        setSize(new java.awt.Dimension(1292, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Gastos_Particulares().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adicionar_GastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_GastoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_adicionar_GastoActionPerformed

    private void adicionar_GastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionar_GastoMouseClicked

        if(Float.parseFloat(valorDoGasto.getText())<=saldo){
            try {
                String desigG= designacaoDoGasto.getText();
                String v= valorDoGasto.getText();
                String localG= localGasto.getText();
                String dataG= dataGasto.getText();
                
                float valorG = Float.parseFloat(v); // converte a String para Float
                
                
                GastosInd g=new GastosInd(desigG, localG, dataG, valorG);
                GastosI ag=new GastosI();
                Humanos h = new Humanos(null, null, null, null);
                //Familia familia = new Familia(null, null, null, null);
                //familia.setIdFamilia(idfamilia);
                h.setIdHumanos(idpessoa);
                
                g.setHumanos(h);
                ag.adicionarGastos(g);
                Menu.pessoa.getIdHumano();
                
                //LISTA DE GASTOS
                g.setDesignacao(desigG);
                g.setLocaldogasto(localG);
                g.setDataGasto(dataG);
                g.setValor(valorG);
                gastos.add(g);
                float valorF=Float.parseFloat(valorDoGasto.getText());
                PrevisaoBD.mudarPRevisao(Menu.pessoa.getIdFamilia(), desigG, valorF,id,0);
                lerTabela();                
                Login.saldo=Login.saldo-saldo;                
            } catch (SQLException ex) {
                Logger.getLogger(Adc_Gastos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "O valor excede o valor previsto");
            
                float resultado = Float.parseFloat(valorDoGasto.getText()) - saldo;
                dispose();
                new Fazer_Credito(String.valueOf(resultado)).setVisible(true);
            
        }        
    }//GEN-LAST:event_adicionar_GastoMouseClicked
    float saldo;
    int id;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            id=Integer.parseInt(String.valueOf(tabelaPr.getValueAt(tabelaPr.getSelectedRow(), 0)));
            String desg= String.valueOf(tabelaPr.getValueAt(tabelaPr.getSelectedRow(), 1));
            String valor= String.valueOf(tabelaPr.getValueAt(tabelaPr.getSelectedRow(), 2));
            designacaoDoGasto.setText(desg);
            saldo=Float.parseFloat(valor);
            valorDoGasto.setText(valor);    
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Seleccione uma alinha");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void valorDoGastoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_valorDoGastoCaretUpdate
        // TODO add your handling code here:
        boolean v=false;
        if(!valorDoGasto.getText().isEmpty()){
            if(Float.parseFloat(valorDoGasto.getText())>saldo){
                JOptionPane.showMessageDialog(null, "Nao podemos ultrapassar o valor estipulado na previsao");                
            }
        }        
    }//GEN-LAST:event_valorDoGastoCaretUpdate

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Selecione uma Linha na Tabela");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            //soma = Float.parseFloat(valorDoGasto.getText());
           // float i = saldo;
            //float valor =   Float.parseFloat(valorDoGasto.getText());
            float resultado = Float.parseFloat(valorDoGasto.getText())- saldo;
            dispose();
            new Fazer_Credito(String.valueOf(resultado)).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adc_Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adc_Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adc_Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adc_Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Adc_Gastos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Adc_Gastos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_Gasto;
    private javax.swing.JTextField dataGasto;
    private javax.swing.JTextField designacaoDoGasto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localGasto;
    private javax.swing.JTable tabelaPr;
    private javax.swing.JTextField valorDoGasto;
    // End of variables declaration//GEN-END:variables
}
