/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VisaodoProjProgIII;

import ClassesdoProjProgIII.Credito;
import ClassesdoProjProgIII.Familia;
import ClassesdoProjProgIII.GastosInd;
import ClassesdoProjProgIII.PrevMensal;
import static VisaodoProjProgIII.Consultar_Gastos.g1;
import static VisaodoProjProgIII.Menu.pessoa;
import controlo.DizimoBD;
import controlo.Familia_Login;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.GastosI;
import controlo.PrevisaoBD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Consulta_Prev extends javax.swing.JFrame {
    PrevisaoBD prev = new PrevisaoBD();

    /** Creates new form Previsao_Mensal */
    public static float valorPrev; 
     public static float p1; 
    public Consulta_Prev() throws SQLException {
        initComponents();
        setSize(1250, 775);
        lerTabela ();
        dispose();
        //valor.setText(Float.toString(PrevisaoBD.somaPrev(idpessoa)));
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void lerTabela () throws SQLException {
           
               DefaultTableModel tb= (DefaultTableModel) tabelaPr.getModel();  
               tb.setNumRows(0);
              
               for(PrevMensal pr:prev.lerP(idfamilia)){
                    tb.addRow(new Object[]{pr.getNomeDoGasto(), pr.getValor()});
               }
        
       }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPr = new javax.swing.JTable();
        actualizar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("TOTAL DISPONIVEL PARA GASTOS: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 500, 440, 40);

        valor.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        getContentPane().add(valor);
        valor.setBounds(620, 500, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setText("KZs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 500, 100, 40);

        tabelaPr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tabelaPr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "NOME DO GASTO", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 150, 900, 270);

        actualizar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar);
        actualizar.setBounds(500, 630, 200, 40);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(100, 630, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/PREVISÃO mENSAL.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, -5, 1240, 730);

        setSize(new java.awt.Dimension(1258, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
         try {
        // TODO add your handling code here:
        p1 = PrevisaoBD.somaPrev(idfamilia) - GastosI.somaGastosI(idpessoa);
        valorPrev =p1;
        valor.setText(Float.toString(valorPrev));
    } catch (SQLException ex) {
        Logger.getLogger(Consultar_Rend.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_Prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_Prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_Prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_Prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Consulta_Prev().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consulta_Prev.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPr;
    private javax.swing.JLabel valor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
