/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import ClassesdoProjProgIII.Humanos;
import static VisaodoProjProgIII.Menu.pessoa;
import controlo.Familia_Login;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import java.util.Arrays;

/**
 *
 * @author HP
 */
public class CriacaoDaFamilia extends javax.swing.JFrame {

    /**
     * Creates new form CriacaoDaFamilia
     */
    public CriacaoDaFamilia() {
        initComponents();
        setSize(1260, 757);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        Conf_senha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        asasa = new javax.swing.JLabel();
        grau = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dataNasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sobreN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CadastrarF = new javax.swing.JButton();
        dataN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(100, 620, 140, 40);
        getContentPane().add(Conf_senha);
        Conf_senha.setBounds(490, 450, 260, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Confirma a Senha");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 420, 230, 22);

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(490, 360, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Senha");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 330, 100, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Grau Parentesco");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 250, 170, 22);

        telC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telCActionPerformed(evt);
            }
        });
        getContentPane().add(telC);
        telC.setBounds(870, 540, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Telefone de Casa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(870, 510, 220, 22);

        telP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telPActionPerformed(evt);
            }
        });
        getContentPane().add(telP);
        telP.setBounds(870, 450, 260, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Telefone Particular");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(870, 420, 190, 22);

        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        getContentPane().add(bairro);
        bairro.setBounds(870, 360, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Bairro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(870, 330, 90, 22);

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco);
        endereco.setBounds(870, 276, 260, 40);

        asasa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        asasa.setText("Endereço");
        getContentPane().add(asasa);
        asasa.setBounds(870, 250, 170, 22);

        grau.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        grau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAI", "MÃE" }));
        getContentPane().add(grau);
        grau.setBounds(490, 276, 260, 40);
        getContentPane().add(email);
        email.setBounds(100, 540, 260, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 510, 130, 22);
        getContentPane().add(dataNasc);
        dataNasc.setBounds(100, 450, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data Nascimento(YYYY/MM/DD)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 420, 310, 20);
        getContentPane().add(sobreN);
        sobreN.setBounds(100, 360, 260, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Sobrenome da familia");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 330, 250, 22);
        getContentPane().add(nome);
        nome.setBounds(100, 276, 260, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 250, 180, 22);

        CadastrarF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CadastrarF.setText("CADASTRAR FAMILIA");
        CadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarF);
        CadastrarF.setBounds(510, 570, 220, 40);

        dataN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/cadastramento de familia.png"))); // NOI18N
        getContentPane().add(dataN);
        dataN.setBounds(0, -3, 1240, 730);

        setSize(new java.awt.Dimension(1262, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFActionPerformed
        // TODO add your handling code here:
        
        String ende= endereco.getText();
        String bair= bairro.getText();
        String telpart= telP.getText();
        String telcasa= telC.getText();
        String senhacad= Arrays.toString(senha.getPassword());
        String Confsenha= Arrays.toString(Conf_senha.getPassword());
        String nomeM= nome.getText();
        String sobreNome= sobreN.getText();
        String datanasci= dataNasc.getText();
        String emailN= email.getText();
        String grauPe=grau.getSelectedItem().toString();
        //h= new Humanos(rs.getString("nome"),rs.getString("email"),rs.getString("tel"),rs.getString("dataNasc"),rs.getString("relacao"), null, rs.getInt("Familia_idfamilia"), rs.getInt("idHumanos"), null,null, null,null);
       // Humanos h=new Humanos(nomeM, emailN, telpart, datanasci, grauPe, sobreNome, ende, bair, telcasa);
        Humanos h = new Humanos(nomeM, emailN, telpart, datanasci, grauPe, senhacad, idfamilia, idpessoa, sobreNome, ende, bair, telcasa) ;
        h.setSenha(senhacad);
        Familia_Login f=new Familia_Login();
        f.CadastrarFamilia(h);
        h.setIdFamilia(f.buscaCod(h.getTel()));
        f.cadastrarPessoa(h);
        dispose();
        new Login().setVisible(true);
        
    }//GEN-LAST:event_CadastrarFActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
  
        
    }//GEN-LAST:event_enderecoActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
      // TODO add your handling code here:
      String bairo= bairro.getText();
    }//GEN-LAST:event_bairroActionPerformed

    private void telPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telPActionPerformed
        // TODO add your handling code here:
        String telpart=telP.getText();
    }//GEN-LAST:event_telPActionPerformed

    private void telCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telCActionPerformed
        // TODO add your handling code here:
        String telcasa=telC.getText();
    }//GEN-LAST:event_telCActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
        String inssenha=senha.getText();
    }//GEN-LAST:event_senhaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
       
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriacaoDaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriacaoDaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriacaoDaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriacaoDaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CriacaoDaFamilia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarF;
    private javax.swing.JPasswordField Conf_senha;
    private javax.swing.JLabel asasa;
    private javax.swing.JTextField bairro;
    private javax.swing.JLabel dataN;
    private javax.swing.JTextField dataNasc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox<String> grau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField sobreN;
    private javax.swing.JTextField telC;
    private javax.swing.JTextField telP;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
