/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import static VisaodoProjProgIII.Consultar_Dizimo.valorD;
import static VisaodoProjProgIII.Menu.pessoa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static VisaodoProjProgIII.Menu.soma_Dizimos;
import controlo.DizimoBD;
import static controlo.Familia_Login.idpessoa;

/**
 *
 * @author HP
 */
public class Dizimos extends javax.swing.JFrame {

    /**
     * Creates new form Dizimo
     */
    public Dizimos() {
        initComponents();
        setSize(1260, 772);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        consultarD = new javax.swing.JButton();
        fornecerD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 620, 140, 40);

        consultarD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        consultarD.setText("CONSULTAR");
        consultarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDActionPerformed(evt);
            }
        });
        getContentPane().add(consultarD);
        consultarD.setBounds(720, 300, 420, 220);

        fornecerD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fornecerD.setText("FORNECER DIZIMO");
        fornecerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecerDActionPerformed(evt);
            }
        });
        getContentPane().add(fornecerD);
        fornecerD.setBounds(100, 300, 420, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/dizimo (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1240, 730);

        setSize(new java.awt.Dimension(1263, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fornecerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecerDActionPerformed
        // TODO add your handling code here:
         boolean p;
        p = pessoa.getGrau().equalsIgnoreCase("Filho");
        if(p == true){
            JOptionPane.showMessageDialog(null,"MEMBRO NAO AUTORIZADO!");
        }else{
            dispose();
            new Fornecer_Dizimos().setVisible(true);
        }  
    }//GEN-LAST:event_fornecerDActionPerformed

    private void consultarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDActionPerformed
        // TODO add your handling code here:
        dispose();
         try {
                    soma_Dizimos = DizimoBD.somaDizimo(idpessoa);
                    valorD = soma_Dizimos;
                    new Consultar_Dizimo().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Dizimo.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_consultarDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dizimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dizimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dizimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dizimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dizimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarD;
    private javax.swing.JButton fornecerD;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
