/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import controlo.Familia_Login;
import ClassesdoProjProgIII.Credito;
import ClassesdoProjProgIII.Humanos;
import ClassesdoProjProgIII.Rendimento;
import controlo.CreditoBD;
import static controlo.Familia_Login.idpessoa;
import controlo.RendimentoBD;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Fazer_Credito extends javax.swing.JFrame {

    /**
     * Creates new form Fazer_Credito
     */
    public Fazer_Credito() {
        initComponents();
        setSize(1250, 775);
        dispose();
    }

    public Fazer_Credito(String valor) {
        initComponents();
        setSize(1250, 775);
        valorConcedido.setText(valor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        localC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataVencimento = new javax.swing.JTextField();
        valorvencimento = new javax.swing.JTextField();
        totalRend = new javax.swing.JTextField();
        dataSituacao = new javax.swing.JTextField();
        valorDivida = new javax.swing.JTextField();
        valorConcedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fazerCred = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel11.setText("YYYY/MM/DD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(830, 340, 110, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("LOCAL DO CREDITO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 500, 190, 20);
        getContentPane().add(localC);
        localC.setBounds(260, 490, 250, 40);

        jLabel8.setText("YYYY/MM/DD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 410, 110, 20);
        getContentPane().add(dataVencimento);
        dataVencimento.setBounds(830, 360, 250, 40);
        getContentPane().add(valorvencimento);
        valorvencimento.setBounds(830, 280, 250, 40);
        getContentPane().add(totalRend);
        totalRend.setBounds(830, 430, 250, 40);
        getContentPane().add(dataSituacao);
        dataSituacao.setBounds(260, 430, 250, 40);
        getContentPane().add(valorDivida);
        valorDivida.setBounds(260, 360, 250, 40);

        valorConcedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorConcedidoActionPerformed(evt);
            }
        });
        getContentPane().add(valorConcedido);
        valorConcedido.setBounds(260, 290, 250, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("DATA DE VENCIMENTO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 370, 200, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("TOTAL DE RENDIMENTO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 440, 200, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("VALOR DE VENCIMENTO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 300, 210, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("DATA DA SITUACAO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 440, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("VALOR EM DIVIDA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(61, 370, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("VALOR CONCEDIDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 300, 160, 20);

        fazerCred.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fazerCred.setText("EFECTUAR CREDITO");
        fazerCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerCredActionPerformed(evt);
            }
        });
        getContentPane().add(fazerCred);
        fazerCred.setBounds(510, 550, 220, 40);

        Voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(100, 620, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/consultar credito (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1230, 720);

        jLabel10.setText("YYYY/MM/DD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(830, 340, 110, 20);

        setSize(new java.awt.Dimension(1252, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Creditos().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void valorConcedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorConcedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorConcedidoActionPerformed

    private void fazerCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerCredActionPerformed
        // TODO add your handling code here:
        String vC= valorConcedido.getText();
        String vD= valorDivida.getText();
        String vV= valorvencimento.getText();
        String tR= totalRend.getText();
        String dataIn= dataSituacao.getText();
        String local= localC.getText();
        String dataFim= dataVencimento.getText();
        
        float valorC = Float.parseFloat(vC);
        float valorDiv = Float.parseFloat(vD);
        float valorV = Float.parseFloat(vV);
        float totalR = Float.parseFloat(tR);
        
        Credito c=new Credito(valorC, valorDiv, valorV, totalR, dataIn, local,dataFim);
        CreditoBD cbd=new CreditoBD();  
        
        Humanos h = new Humanos(null, null, null, null);
        h.setIdHumanos(idpessoa);
        c.setHumanos(h);
        cbd.adicionarCredito(c);
        
        Rendimento r=new Rendimento("Credito", dataIn, valorC);
        r.setHumanos(h);
        RendimentoBD rbd = new RendimentoBD();
        rbd.adicionarRendimento(r);
        
        dispose();
        new Creditos().setVisible(true);
    }//GEN-LAST:event_fazerCredActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fazer_Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fazer_Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fazer_Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fazer_Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fazer_Credito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField dataSituacao;
    private javax.swing.JTextField dataVencimento;
    private javax.swing.JButton fazerCred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField localC;
    private javax.swing.JTextField totalRend;
    private javax.swing.JTextField valorConcedido;
    private javax.swing.JTextField valorDivida;
    private javax.swing.JTextField valorvencimento;
    // End of variables declaration//GEN-END:variables
}
