/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import ClassesdoProjProgIII.Familia;
import ClassesdoProjProgIII.Humanos;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Meu_Perfil extends javax.swing.JFrame {
    //public static Humanos pessoa;
      public static Humanos pessoa;
      public static Familia familia;
      
    public Meu_Perfil(Humanos h) {
        initComponents();
        setSize(1263, 765);
        pessoa=h;
        nome.setText(h.getNome().toUpperCase());
        email.setText(h.getEmail().toUpperCase());
        grau.setText(h.getGrau().toUpperCase());
        dataNasc.setText(h.getData().toUpperCase());
        tel.setText(h.getTele().toUpperCase());
        //sobrenome.setText(f.getSobrenome().toUpperCase());*/   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sobrenome = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        dataNasc = new javax.swing.JLabel();
        grau = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        eliminarMembro = new javax.swing.JButton();
        adc_Membros = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sobrenome.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        getContentPane().add(sobrenome);
        sobrenome.setBounds(320, 440, 330, 0);

        tel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tel.setText("A");
        getContentPane().add(tel);
        tel.setBounds(910, 250, 320, 24);

        dataNasc.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        dataNasc.setText("A");
        getContentPane().add(dataNasc);
        dataNasc.setBounds(910, 340, 200, 30);

        grau.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grau.setText("A");
        getContentPane().add(grau);
        grau.setBounds(580, 420, 160, 30);

        email.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        email.setText("A");
        getContentPane().add(email);
        email.setBounds(170, 340, 440, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("EMAIL: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 340, 110, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("NUMERO DE TELEF: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 250, 280, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("DATA NASCIMENTO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 340, 270, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("GRAU PARENTESCO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 420, 260, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 240, 150, 29);

        nome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nome.setText("A");
        getContentPane().add(nome);
        nome.setBounds(170, 240, 400, 30);

        eliminarMembro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        eliminarMembro.setText("ELIMINAR MEMBRO DA FAMILIA");
        eliminarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMembroActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarMembro);
        eliminarMembro.setBounds(880, 450, 320, 90);

        adc_Membros.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adc_Membros.setText("ADICIONAR MEMBRO DA FAMILIA");
        adc_Membros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adc_MembrosActionPerformed(evt);
            }
        });
        getContentPane().add(adc_Membros);
        adc_Membros.setBounds(880, 570, 320, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 620, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/dizimo (8).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1240, 710);

        setSize(new java.awt.Dimension(1261, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adc_MembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adc_MembrosActionPerformed
        // TODO add your handling code here:
      boolean p;
        p = pessoa.getGrau().equalsIgnoreCase("Filho");
        if(p == true){
            JOptionPane.showMessageDialog(null,"MEMBRO NAO AUTORIZADO!");
        }else{
            dispose();
            new Adc_Membros().setVisible(true);
        }
    }//GEN-LAST:event_adc_MembrosActionPerformed

    private void eliminarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMembroActionPerformed
        boolean p;
        p = pessoa.getGrau().equalsIgnoreCase("Filho");
        if(p == true){
            JOptionPane.showMessageDialog(null,"MEMBRO NAO AUTORIZADO!");
        }else{
            dispose();
            new Eliminar_membro().setVisible(true);
        }   
        
    }//GEN-LAST:event_eliminarMembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meu_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meu_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meu_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meu_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meu_Perfil(pessoa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adc_Membros;
    private javax.swing.JLabel dataNasc;
    private javax.swing.JButton eliminarMembro;
    private javax.swing.JLabel email;
    private javax.swing.JLabel grau;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel sobrenome;
    private javax.swing.JLabel tel;
    // End of variables declaration//GEN-END:variables
}
