/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import static VisaodoProjProgIII.Menu.pessoa;
import static VisaodoProjProgIII.Menu.soma_poupanca;
import controlo.DizimoBD;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.GastosI;
import controlo.PoupancaBD;
import static VisaodoProjProgIII.Consultar_Pou.valorP;
import controlo.PrevisaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class Poupancas extends javax.swing.JFrame {

    /**
     * Creates new form Poupanca
     */
   
    public Poupancas() {
        initComponents();
        setSize(1240, 742);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consulta = new javax.swing.JButton();
        adc_poupanca = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        consulta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        consulta.setText("CONSULTAR");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        getContentPane().add(consulta);
        consulta.setBounds(720, 300, 420, 220);

        adc_poupanca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adc_poupanca.setText("ADICIONAR VALORES ");
        adc_poupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adc_poupancaActionPerformed(evt);
            }
        });
        getContentPane().add(adc_poupanca);
        adc_poupanca.setBounds(100, 300, 420, 220);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(100, 620, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/Novo Membro (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 1240, 700);

        setSize(new java.awt.Dimension(1266, 762));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
        dispose();
         try {
                    soma_poupanca = PoupancaBD.somapoupanca(idfamilia);
                    valorP = soma_poupanca;
                    new Consultar_Pou().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Pou.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_consultaActionPerformed

    private void adc_poupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adc_poupancaActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new Adc_Valores_Pou().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Poupancas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adc_poupancaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poupancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poupancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poupancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poupancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poupancas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adc_poupanca;
    private javax.swing.JButton consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
