/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VisaodoProjProgIII;

import ClassesdoProjProgIII.Familia;
import ClassesdoProjProgIII.GastosInd;
import ClassesdoProjProgIII.PrevMensal;
import static VisaodoProjProgIII.Login.saldo;
import static VisaodoProjProgIII.Menu.pessoa;
import controlo.Familia_Login;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.PrevisaoBD;
import controlo.RendimentoBD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Previsao_Mensal extends javax.swing.JFrame {

    /** Creates new form Previsao_Mensal */
    public Previsao_Mensal() {
        try {
            initComponents();
            setSize(1250, 775);
            dispose();
                float desc1=PrevisaoBD.descontos1(idpessoa) + PrevisaoBD.somaPrev(idfamilia);
                float desc2=PrevisaoBD.descontos2(idfamilia);
                Login.saldo= RendimentoBD.somaRendimentos(idpessoa)-(desc1+desc2);
                Rendimento.setText(Float.toString(saldo));
        } catch (SQLException ex) {
            Logger.getLogger(Previsao_Mensal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public ArrayList<PrevMensal> pv = new  ArrayList<>();
    
     public void lerTabela () {
              DefaultTableModel tb= (DefaultTableModel) tabelaP.getModel();  
              tb.setNumRows(0);
             for(PrevMensal pm: pv){
                tb.addRow(new Object[]{pm.getNomeDoGasto(),pm.getValor()});
            }
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        R = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaP = new javax.swing.JTable();
        adc_gastoMensal = new javax.swing.JButton();
        valorGastoMensal = new javax.swing.JTextField();
        nomedoGastoMensal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        Rendimento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        R.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        R.setText("KZS");
        getContentPane().add(R);
        R.setBounds(690, 230, 60, 25);

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(990, 590, 120, 30);

        editar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(990, 640, 120, 30);

        tabelaP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tabelaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "NOME DO GASTO", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 430, 690, 240);

        adc_gastoMensal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adc_gastoMensal.setText("ADICIONAR PREVISAO");
        adc_gastoMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adc_gastoMensalActionPerformed(evt);
            }
        });
        getContentPane().add(adc_gastoMensal);
        adc_gastoMensal.setBounds(500, 360, 220, 40);
        getContentPane().add(valorGastoMensal);
        valorGastoMensal.setBounds(710, 300, 270, 40);
        getContentPane().add(nomedoGastoMensal);
        nomedoGastoMensal.setBounds(250, 300, 270, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("VALOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 310, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 310, 60, 20);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(100, 630, 140, 40);

        Rendimento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Rendimento.setText("0000000");
        getContentPane().add(Rendimento);
        Rendimento.setBounds(590, 230, 160, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Rendimento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 230, 110, 22);

        jButton1.setText("Adicionar Rendimento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 480, 190, 29);

        jButton2.setText("Fazer Credito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1070, 430, 150, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/PREVISÃO mENSAL.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, -5, 1240, 730);

        setSize(new java.awt.Dimension(1258, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void adc_gastoMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adc_gastoMensalActionPerformed
        // TODO add your handling code here:
        String nomeGasto= nomedoGastoMensal.getText();
        String v= valorGastoMensal.getText();
        float valor =   Float.parseFloat(v);
        float r     =   Float.parseFloat(Rendimento.getText()); 
        if(valor<=r)
        {
            if(PrevisaoBD.Existe(nomeGasto, Menu.pessoa.getIdFamilia()))
            {
                try {
                    PrevisaoBD.alterarPrevi(Menu.pessoa.getIdFamilia(), nomeGasto, valor);
                } catch (SQLException ex) {
                    Logger.getLogger(Previsao_Mensal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                float valorGasto = Float.parseFloat(v);
                PrevMensal p=new PrevMensal(valorGasto, nomeGasto);
                PrevisaoBD pbd = new PrevisaoBD ();

                Familia f = new Familia(null, null, null, null);

                f.setIdFamilia(idfamilia);
                p.setFamilia(f);
                pbd.adicionarPrevisao(p);

                //LER TABELA
                p.setValor(valorGasto);
                p.setNomeDoGasto(nomeGasto);

                pv.add(p);
                lerTabela();
                r-=valor;
                Rendimento.setText(""+r);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "SALDO INSUFICIENTE!\nFaça Credito ou Adicione Rendimento");
        }       
    }//GEN-LAST:event_adc_gastoMensalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            float valor =   Float.parseFloat(valorGastoMensal.getText());
            float r     =   Float.parseFloat(Rendimento.getText());   
            float resultado = valor-r;
            dispose();
            new Adc_Rendimento(String.valueOf(resultado)).setVisible(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "INFORME O VALOR!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{            
            float valor =   Float.parseFloat(valorGastoMensal.getText());
            float r     =   Float.parseFloat(Rendimento.getText());   
            float resultado = valor-r;
            dispose();
            new Fazer_Credito(String.valueOf(resultado)).setVisible(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "INFORME O VALOR!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Previsao_Mensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Previsao_Mensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Previsao_Mensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Previsao_Mensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Previsao_Mensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R;
    private javax.swing.JLabel Rendimento;
    private javax.swing.JButton adc_gastoMensal;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomedoGastoMensal;
    private javax.swing.JTable tabelaP;
    private javax.swing.JTextField valorGastoMensal;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
