/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisaodoProjProgIII;

import static VisaodoProjProgIII.Consultar_Rend.v1;
import static VisaodoProjProgIII.Consultar_Rend.v2;
import static VisaodoProjProgIII.Consultar_Rend.valorR;
import static VisaodoProjProgIII.Menu.soma_Rendimento;
import static VisaodoProjProgIII.Menu.pessoa;
import controlo.CreditoBD;
import static controlo.Familia_Login.idfamilia;
import static controlo.Familia_Login.idpessoa;
import controlo.PoupancaBD;
import controlo.PrevisaoBD;
import controlo.RendimentoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Rendimentos extends javax.swing.JFrame {

    /**
     * Creates new form Rendimento
     */
    public Rendimentos() {
        initComponents();
        setSize(1257, 767);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        consultar_rendimento = new javax.swing.JButton();
        adc_rendimento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(100, 620, 140, 40);

        consultar_rendimento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        consultar_rendimento.setText("CONSULTAR ");
        consultar_rendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_rendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(consultar_rendimento);
        consultar_rendimento.setBounds(708, 330, 440, 220);

        adc_rendimento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adc_rendimento.setText("ADICIONAR");
        adc_rendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adc_rendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(adc_rendimento);
        adc_rendimento.setBounds(100, 330, 420, 220);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(761, 93, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VisaodoProjProgIII/Imagens/dizimo (3).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1240, 740);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 180, 110, 30);

        setSize(new java.awt.Dimension(1259, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu(pessoa).setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void consultar_rendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_rendimentoActionPerformed
        // TODO add your handling code here:
        dispose();
         try {
        // TODO add your handling code here:
        soma_Rendimento = RendimentoBD.somaRendimentos(idpessoa);
        soma_Rendimento = soma_Rendimento - PoupancaBD.somapoupanca(idpessoa);
        soma_Rendimento = soma_Rendimento - PrevisaoBD.somaPrev(idfamilia);
        valorR = soma_Rendimento;
        
    } catch (SQLException ex) {
        Logger.getLogger(Consultar_Rend.class.getName()).log(Level.SEVERE, null, ex);
    }
        try {
                    new Consultar_Rend().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Rend.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_consultar_rendimentoActionPerformed

    private void adc_rendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adc_rendimentoActionPerformed
        // TODO add your handling code here:
        boolean p;
        p = pessoa.getGrau().equalsIgnoreCase("Filho");
        if(p == true){
            JOptionPane.showMessageDialog(null,"MEMBRO NAO AUTORIZADO!");
        }else{
            dispose();
           new Adc_Rendimento().setVisible(true);
        }  
    }//GEN-LAST:event_adc_rendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rendimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rendimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rendimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rendimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rendimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adc_rendimento;
    private javax.swing.JButton consultar_rendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
